export default {
  addTxt: {
    width: '100%',
    borderWidth: 1,
    padding: 10,
    borderRadius: 5,
  },
  btn: {
    width: '49%',
    marginTop: 10,
    marginVertical: 5,
    marginRight: 5,
    paddingTop: 5,
    paddingBottom: 5,
    backgroundColor: '#43a047',
    borderRadius: 5,
    borderWidth: 0,
  },
  BgRed: { backgroundColor: '#e65100' },
  BgBlue: { backgroundColor: '#01579b' },
  BgGreen: { backgroundColor: '#43a047' },
  checkbox: {
    alignSelf: 'center',
    height: 15,
    width: 15,
    borderWidth: 2,
    borderColor: 'black',
  },
  doneTasks: {
    textDecorationLine: 'line-through',
    textDecorationStyle: 'solid',
    fontWeight: 'bold',
  },
  txtBold: {
    fontWeight: 'bold',
  },
  dNone: {
    display: 'none',
  },
  errClr: {
    backgroundColor: 'pink',
  },
  errItem: {
    backgroundColor: 'pink',
    color: 'white',
    padding: 5,
  },
  fContainer: { flexDirection: 'row', marginTop: 5 },
  h15: { height: 15 },
  h30: { height: 30 },
  flexRow: {
    flexDirection: 'row',
  },
  flex1: { flex: 1, height: 5 },
  fs18: { fontSize: 18 },
  fs20: {
    fontSize: 20,
  },
  goalItem: { backgroundColor: 'gainsboro', padding: 5 },
  inputsSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  justify: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  mt5: { marginTop: 5 },
  mr10: { marginRight: 10 },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'gainsboro',
    borderRadius: 15,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginHorizontal: 20,
    marginVertical: 380,
  },
  screen: {
    paddingTop: 50,
    padding: 30,
  },
  successClr: {
    borderColor: '#32CD32',
    borderWidth: 2,
  },
};
